elastic-ipfs/bitswap-peer

src/service.js

`addBlockPresence` returns `false` when the passed `presence` is _not_ added to the message because it got too big.
Currently the `presence` is only sent when this occurs and it should be the opposite.

fix: send DontHave for non-present CIDs

---

src/protocol.js

According to [this comment](https://github.com/ipfs/go-bitswap/blob/master/message/pb/message.proto#L16) the CID is v0 in bitswap v1.0 but v1 in v1.1 and v1.2. However, there's no code in go-bitswap that does this conversion:
* https://github.com/ipfs/go-bitswap/blob/35b5af95d30319094d448df61b7286b72a8c7b16/message/message.go#L118
* https://github.com/ipfs/go-bitswap/blob/35b5af95d30319094d448df61b7286b72a8c7b16/message/message.go#L455
I've also observed that ipfs-check thinks the peer does not respond when asked for a v0 CID. We receive a message from the remote peer but it ends up comparing a v0 CID with a v1 CID and eventually times out.
See https://github.com/aschmahmann/ipfs-check/blob/f4ba59752e733f6f9bb30647f6eeebbbb8b2062e/bitswap.go#L87-L118
I added some logging to ipfs-check to …

fix: do not convert v0 to v1 CID

---

README.md

For some reason this was not being recognised as a h1.
Also update with new name.

fix: title on README

---

src/service.js

An 'error' listener is being attached on the incoming connection...but when sending the wantlist back to the peer with the wanted blocks no event listener is added to the outgoing connection.
I believe this is pulling the process down when there's an error in the outgoing connection.

fix: catch emitted error on outgoing connection

---

src/peer-id.js

Readiness Probes are using this functionality, so logs can start looking like this:
(New line every 5s)
```
{"level":30,"time":"2022-06-24T18:02:27.018Z","msg":"Downloading PeerId from s3://us-west-2-staging-ep-bitswap-config/peerId.json"}
{"level":30,"time":"2022-06-24T18:02:32.018Z","msg":"Downloading PeerId from s3://us-west-2-staging-ep-bitswap-config/peerId.json"}
{"level":30,"time":"2022-06-24T18:02:37.018Z","msg":"Downloading PeerId from s3://us-west-2-staging-ep-bitswap-config/peerId.json"}
{"level":30,"time":"2022-06-24T18:02:42.018Z","msg":"Downloading PeerId from s3://us-west-2-staging-ep-bitswap-config/peerId.json"}
{"level":30,"time":"2022-06-24T18:02:47.018Z","msg":"Downloading PeerId from s3://us-west-2-staging-ep-bitswap-config/peerId.json"} …
```

Reduce log level when downloading peerId

---

src/service.js

Would be useful to quickly know the CID of the block that was not found. The `entry` in the log does contain the CID but it is serialized as an object not a string so not super useful.

feat: improve block not found message

---

package-lock.json
package.json
src/networking.js
src/service.js
test/bitswap-1.2.0.test.js

This PR fixes closing incoming and outgoing duplex streams properly. This will hopefully resolve at least 1 memory leak.
There were 2 issues here:
1. For incoming streams, we never closed our side for writing. i.e. when we got a new incoming stream and finished receiving all the data we didn't close our side for writing (and we don't write to the incoming stream anyway).
2. For outgoing streams, we never closed our side for reading. i.e. the stream was held open, awaiting a read (and we never read anything when sending data back to the peer anyway).

fix: close streams properly

---

README.md
metrics.yml
src/config.js
src/service.js
test/service.test.js

This PR adds an LRU block data cache. I realised we only have an LRU cache for block _info_ not block _data_ 🤦‍♂️.
The default size of this cache is 1,000 items which is...tiny. Blocks in dotstorage currently cannot be >1MB in size so as a rough guide we might want to add about 500MB of memory for every 1,000 items as typically blocks will be significantly smaller than 1MB (256kb for regular IPFS blocks).
Aside, why didn't we use https://www.npmjs.com/package/lru-cache? The one we're using only allows us to set the number of items and I'd ideally like to set the maximum byte size. Maybe that can be changed in a follow up PR.
Once this is merged, I'd like to follow up with a PR to prefetch blocks into the cache.

feat: add LRU block data cache

---

README.md
package-lock.json
package.json
src/config.js
src/service.js

I'd like to disable the `keep-alive` to check if the memory-leak is related to it, and if performance decrease

feat: options for peers keep-alive

---

README.md

Remove AWS specific env vars and link to AWS configuration doc. Also removing CICD specific environment variables. Current doc is generating confusion. Developers often think that is necessary to configure long living keys inside lambda and EC2

Improve docs by removing confusion with AWS env variables

---

README.md

Adds contribute and release process guidelines similarly to https://github.com/elastic-ipfs/indexer-lambda/pull/74

docs: add contribute and release process to readme

---

src/handler.js
src/storage.js
test/handler.test.js

This PR makes sure we do not send messages with block bytes for entries in the wantlist that have cancel boolean `true`.
In current behaviour, we perform a check for cancel message in [storage.js#L109-L112](https://github.com/elastic-ipfs/bitswap-peer/blob/main/src/storage.js#L109-L112) and [storage.js#L174-L177](https://github.com/elastic-ipfs/bitswap-peer/blob/main/src/storage.js#L174-L177). This check makes sure we do [not read bytes from S3 and add them to cache](https://github.com/elastic-ipfs/bitswap-peer/blob/main/src/storage.js#L148-L153). However, in the bitswap [protocol handler](https://github.com/elastic-ipfs/bitswap-peer/blob/main/src/handler.js#L122-L126) we also return these messages from `batchFetch` function and call `batchResponse` function with them to send bitswap …

fix: not send messages when cancel entry in wantlist

---

metrics.yml
package-lock.json
package.json
src/handler.js
src/service.js
test/handler.test.js

This PR adds handling of cancel messages from inflight operations. Using `p-queue` together with Abort Signal all the way would be my ideal solution, but that would require a huge refactor that would mean a long time to work on this.
Implementation details:
- added `inProcessingWantBlocks` and `inProcessingWantHaves` Maps to the handler context (each connection has its own context)
- decoupled previous `batchFetch` function into two function, with an initial step just for getting a normalized wantList with arrays for `wantedBlocks`, `wantedHave` and `canceled`
- `wantedBlocks` and `wantedHave` added to respective processing maps in the start of fetching, and canceled blocks flagged in respective processing maps (if still existing and not previously addressed)
- cleanup `inProcessing` maps …

feat: handle cancel messages

---

src/handler.js
src/service.js
test/handler.test.js

Fixes cancel message check on LRU.
Couple of issues:
- `end:received` can happen on a normal connection when stream is flushed, but connection is still running
- `block.type` would actually work with one type of requests, but not both
- `block.wantType` can be 0, and therefore flipped if...else

fix: cancel message check

---

src/service.js

Doing some extra tests with dev setup, noticed another issue.
Looks like depending on how messages are propagated in bitswap stream (likely when stream is fully flushed), the write side stream is closed and a new one is open when more messages are sent. This was resulting in a new state where 2 LRU instances can exist for same connection but different streams. This moves the scope to the connection level on `peer:connect` and `peer:disconnect`, making my local tests with dev environment not having this sporadic cancels not fulfilled

fix: cancel state at connection scope instead of stream

---

metrics.yml
package-lock.json
src/handler.js

Adds a metric `bitswap-sent-cid-prefix` with lables for CID prefix values.
Definition of CID prefix: https://github.com/ipfs/go-cid/blob/829c826f6be23320846f4b7318aee4d17bf8e094/cid.go#L542-L554

feat: add metric counters for sent block by CID prefix

---

src/handler.js

Use just the fields for very common values we care about.
refs https://github.com/elastic-ipfs/bitswap-peer/pull/206#issuecomment-1523447757

fix: mitigate cardinality explosion

---

src/handler.js

Don't count block "have" responses, only sent block data responses.

fix: count sent blocks not haves

---

.github/workflows/shared-build.yaml
package-lock.json
package.json

its error prone. if we forget to update the version we overwrite an existing tag.
we already have timestamp based tags. just use those.
fixes: https://github.com/elastic-ipfs/elastic-ipfs/issues/29

fix: dont use package version for image tag

---

src/http-server.js

prom counters are _up_ only. we should not be resetting them after each scrape.
duration histograms are also designed to accumulate information over time, they should not need to be reset either.
fixes: https://github.com/elastic-ipfs/elastic-ipfs/issues/35
License: MIT

fix: dont reset counters & durations after each scrape
